export { default as ChevronLeftFilled } from './chevronLeftFilled'
export { default as ChevronRightFilled } from './chevronRightFilled'
export { default as SkipNextFilled } from './skipNextFilled'
export { default as SkipPreviousFilled } from './skipPreviousFilled'
export { default as Star } from './star'
export { default as StarOutline } from './star-outline'
export { default as Logo } from './vk-logo'
